-- =============================================================================
-- Importació puntual de fitxes (llistat rebut del client).
-- Executa'l UNA SOLA VEGADA a l'SQL Editor de Supabase, després de tenir
-- l'schema.sql ja aplicat (necessita les zones, tipus i equips actuals).
-- =============================================================================

-- Equip nou necessari per a aquest lot (la resta d'equips ja existien).
insert into public.teams (name) values ('Piscines Ferron')
on conflict (name) do nothing;

insert into public.tickets (title, description, zone_id, work_type_id, assignee_id, assignee_team_id, created_by)
select
  v.title,
  v.description,
  (select id from public.zones where name = v.zone_name),
  (select id from public.work_types where name = v.work_type_name),
  (select id from public.profiles where email = v.assignee_email),
  (select id from public.teams where name = v.assignee_team),
  (select id from public.profiles where email = 'marc.camara@gmail.com')
from (values
  ('Reparacions veïns', 'Reparacions veïns', 'General interior', null, null, 'House Habitat'),
  ('El pany de la terrassa no transitable està rallat', 'El pany de la terrassa no transitable està rallat', 'General interior', null, null, 'House Habitat'),
  ('Entregar claus: porta terrassa no transitable, garatge, exterior, etc.', 'Entregar claus: porta terrassa no transitable, garatge, exterior, etc.', 'General interior', null, null, 'House Habitat'),
  ('Documentació House Habitat final d''obra', 'Documentació House Habitat final d''obra', 'General interior', 'Documentació / Legalitzacions', null, 'House Habitat'),
  ('Documentació House Habitat primera ocupació', 'Documentació House Habitat primera ocupació', 'General interior', 'Documentació / Legalitzacions', null, 'House Habitat'),
  ('Línia de vida', 'Línia de vida', 'General interior', null, null, 'House Habitat'),
  ('Butlletí instal·lació Aigua', 'Butlletí instal·lació Aigua', 'General interior', 'Documentació / Legalitzacions', null, 'HH - RAX'),
  ('Butlletí instal·lació elèctrica', 'Butlletí instal·lació elèctrica', 'General interior', 'Documentació / Legalitzacions', null, 'HH - RAX'),
  ('La llum no s''apaga', 'La llum no s''apaga', 'Traster P1', 'Electricitat', null, 'HH - RAX'),
  ('Carxofa descentrada. Fer proposta de placa i si no convenç la solució moure carxofa', 'Carxofa descentrada. Fer proposta de placa i si no convenç la solució moure carxofa', 'Bany suite', 'Fontaneria', null, 'House Habitat'),
  ('Barana costat dret (pujant)', 'Barana costat dret (pujant)', 'Escales', null, null, 'House Habitat'),
  ('Tapar cable entre barana i terra (a dalt del passamans esquerre escala)', 'Tapar cable entre barana i terra (a dalt del passamans esquerre escala)', 'Escales', 'Electricitat', null, 'House Habitat'),
  ('Polsador escales part superior', 'Polsador escales part superior', 'Escales', 'Electricitat', null, 'HH - RAX'),
  ('Video porter casa', 'Video porter casa', 'Façana', 'Electricitat', null, 'HH - RAX'),
  ('Finalitzar SATE zona olivera', 'Finalitzar SATE zona olivera', 'Façana', 'Aïllament / Impermeabilització', null, 'House Habitat'),
  ('Neteja SATE', 'Neteja SATE', 'Façana', 'Neteja', null, 'House Habitat'),
  ('Resoldre trobada columna - part inferior cantonada sala-terrassa', 'Resoldre trobada columna - part inferior cantonada sala-terrassa', 'Façana', null, null, 'House Habitat'),
  ('Revisar tapeta', 'Revisar tapeta', 'Habitació 2', null, null, 'House Habitat'),
  ('Blackouts', 'Blackouts', null, null, null, 'House Habitat'),
  ('El quadre de la instal·lació fotovoltaica també ha d''estar correctament identificat…', 'El quadre de la instal·lació fotovoltaica també ha d''estar correctament identificat amb la seva corresponent retolació.', 'Fotovoltàica', null, null, 'Maynou'),
  ('Posta a punt', 'Posta a punt', 'Fotovoltàica', null, null, 'Maynou'),
  ('Documentació', 'Documentació', 'Fotovoltàica', 'Documentació / Legalitzacions', null, 'Maynou'),
  ('Penjar i senyalitzar l''extintor portàtil, juntament amb el contracte de manteniment.', 'Penjar i senyalitzar l''extintor portàtil, juntament amb el contracte de manteniment.', 'Garatge', null, 'marc.camara@gmail.com', null),
  ('Porta tallafoc: que es tanqui sola (ja comentat en visita d''obra.)', 'Porta tallafoc: que es tanqui sola (ja comentat en visita d''obra.)', 'Garatge', 'Fusteria', null, 'House Habitat'),
  ('Segellar el pas dels tubs corrugats que alimenten la màquina exterior a la zona del traster.', 'Segellar el pas dels tubs corrugats que alimenten la màquina exterior a la zona del traster.', 'Garatge', null, null, 'HH - RAX'),
  ('Repassos de pintura', 'Repassos de pintura', 'General interior', 'Pintura', null, 'House Habitat'),
  ('Neteja', 'Neteja', 'General interior', 'Neteja', null, 'House Habitat'),
  ('?? Segellar els tapajuntes de les portes amb la divisòria.', '?? Segellar els tapajuntes de les portes amb la divisòria.', 'General interior', 'Remats i neteja', null, 'House Habitat'),
  ('Posar persianes', 'Posar persianes', 'General interior', 'Finestres', null, 'House Habitat'),
  ('Pantalles domòtica', 'Pantalles domòtica', 'General interior', 'Electricitat', null, 'HH - 9Habitat'),
  ('Fer gual', 'Fer gual', 'Tanca', 'Paviment', null, 'House Habitat'),
  ('Preparació il·luminació', 'Preparació il·luminació', 'Jardí', 'Electricitat', null, 'HH - RAX'),
  ('Boques aigua per rec', 'Boques aigua per rec', 'Jardí', 'Fontaneria', null, 'HH - RAX'),
  ('Tapar cables - Tub del diàmetre adequat tallat longitudinalment', 'Tapar cables - Tub del diàmetre adequat tallat longitudinalment', 'Jardí', 'Electricitat', null, 'House Habitat'),
  ('Retirar WC etc.', 'Retirar WC etc.', 'Jardí', 'Remats i neteja', null, 'House Habitat'),
  ('Acabar paviment Zona piscina', 'Acabar paviment Zona piscina', 'Jardí', 'Paviment', null, 'House Habitat'),
  ('Tapes dipòsit i arquetes', 'Tapes dipòsit i arquetes', 'Jardí', 'Sanejament', null, 'House Habitat'),
  ('Instal·lar bomba dipòsit pluvials', 'Instal·lar bomba dipòsit pluvials', 'Jardí', 'Fontaneria', null, 'House Habitat'),
  ('Sellar trobada entre reixa de canal i sate al garatge', 'Sellar trobada entre reixa de canal i sate al garatge', 'Façana', 'Aïllament / Impermeabilització', null, 'House Habitat'),
  ('Barbacoa', 'Barbacoa', 'Jardí', null, null, 'House Habitat'),
  ('Ocultació tubs sortida ventilació', 'Ocultació tubs sortida ventilació', 'Jardí', 'Clima', null, 'House Habitat'),
  ('Pèrgola', 'Pèrgola', 'Jardí', null, null, 'Abrisud'),
  ('Domotitzar pèrgola', 'Domotitzar pèrgola', 'Jardí', 'Electricitat', null, 'House Habitat'),
  ('Il·luminació entrada: llums terra, sostre i tira led', 'Il·luminació entrada: llums terra, sostre i tira led', 'Jardí', 'Electricitat', null, 'House Habitat'),
  ('Explicar-nos manteniment', 'Explicar-nos manteniment', 'Piscina', null, null, 'Piscines Ferron'),
  ('Led barana escala', 'Led barana escala', 'Rebedor', 'Electricitat', null, 'House Habitat'),
  ('Sensors moviment inici i final escala', 'Sensors moviment inici i final escala', 'Rebedor', 'Electricitat', null, 'House Habitat'),
  ('Evaluar com intercanviar la rentadora i l''assecadora.', 'Evaluar com intercanviar la rentadora i l''assecadora.', 'Safareig', null, null, 'House Habitat'),
  ('Connexio robot aspirador a electricitat, presa d''aigua i desaigüe.', 'Connexio robot aspirador a electricitat, presa d''aigua i desaigüe.', 'Safareig', null, null, 'House Habitat'),
  ('Pintura impermeable i segellar el sobre de l''aigüera amb la paret.', 'Pintura impermeable i segellar el sobre de l''aigüera amb la paret.', 'Safareig', 'Pintura', null, 'House Habitat'),
  ('Repassar la pintura i paret sobretot la que hi ha entre porta i armari de caixes', 'Repassar la pintura i paret sobretot la que hi ha entre porta i armari de caixes', 'Safareig', 'Pintura', null, 'House Habitat'),
  ('Cubeta per contenir escapes', 'Cubeta per contenir escapes', 'Sala màquines', 'Sanejament', null, 'House Habitat'),
  ('Comptadors aigua varis (piscina i rec)', 'Comptadors aigua varis (piscina i rec)', 'Sala màquines', 'Fontaneria', null, 'House Habitat'),
  ('Regulador de pressió (a tanca)', 'Regulador de pressió (a tanca)', 'Sala màquines', 'Fontaneria', null, 'House Habitat'),
  ('Vàlvula domotitzada per obrir i tancar.', 'Vàlvula domotitzada per obrir i tancar.', 'Sala màquines', null, null, 'House Habitat'),
  ('Substituir el peu del vas d''expansió.', 'Substituir el peu del vas d''expansió.', 'Sala màquines', 'Fontaneria', null, 'House Habitat'),
  ('Substituir dos marcs complets amb els seus tapajuntes, afectats per la fuita, i revisar que el punt de la fuita…', 'Substituir dos marcs complets amb els seus tapajuntes, afectats per la fuita, i revisar que el punt de la fuita no presenti corrosió.', 'Sala màquines', 'Fontaneria', null, 'House Habitat'),
  ('Etiquetar les claus de pas.', 'Etiquetar les claus de pas.', 'Sala màquines', 'Fontaneria', null, 'HH - RAX'),
  ('Posta a punt instal·lacions', 'Posta a punt instal·lacions', 'Sala màquines', null, null, 'HH - RAX'),
  ('Tapes dels quadre de domòtica.', 'Tapes dels quadre de domòtica.', 'Sala màquines', 'Electricitat', null, 'HH - RAX'),
  ('Llum: està blanca encara, s''ha de calibrar', 'Llum: està blanca encara, s''ha de calibrar', 'Sala P1', 'Electricitat', null, 'HH - RAX'),
  ('Vestir interior moble sota escala pendent', 'Vestir interior moble sota escala pendent', 'Sala-Cuina-Menjador', 'Mobiliari', null, 'House Habitat'),
  ('Leds moble vitrina', 'Leds moble vitrina', 'Sala-Cuina-Menjador', 'Electricitat', null, 'HH - Solanes'),
  ('Leds sota moble', 'Leds sota moble', 'Sala-Cuina-Menjador', 'Electricitat', null, 'HH - Solanes'),
  ('Sòcol marbre moble nevera', 'Sòcol marbre moble nevera', 'Sala-Cuina-Menjador', 'Mobiliari', null, 'HH - Solanes'),
  ('Acabat part superior cuina', 'Acabat part superior cuina', 'Sala-Cuina-Menjador', 'Mobiliari', null, 'HH - Solanes'),
  ('Pèndol sobre taula', 'Pèndol sobre taula', 'Sala-Cuina-Menjador', 'Electricitat', null, 'House Habitat'),
  ('Amagar el cable del Fossejat per Il·luminació i Cortiner de la corredera B1 + encintar la trobada entre el sostre…', 'Amagar el cable del Fossejat per Il·luminació i Cortiner de la corredera B1 + encintar la trobada entre el sostre i la vertical.', 'Sala-Cuina-Menjador', 'Electricitat', null, 'House Habitat'),
  ('Instal·lar nevera vins - Falta tapeta', 'Instal·lar nevera vins - Falta tapeta', 'Sala-Cuina-Menjador', 'Mobiliari', null, 'House Habitat'),
  ('Instal·lar microones', 'Instal·lar microones', 'Sala-Cuina-Menjador', 'Mobiliari', null, 'House Habitat'),
  ('Porta de vidre entre zona menjador-sala estar i rebedor amb part fixa de dalt de la porta de vidre', 'Porta de vidre entre zona menjador-sala estar i rebedor amb part fixa de dalt de la porta de vidre', 'Sala-Cuina-Menjador', 'Fusteria', null, 'House Habitat'),
  ('Encontre paviment exterior amb balconera: perfil/tapeta metàl·lica tal i com vam parlar', 'Encontre paviment exterior amb balconera: perfil/tapeta metàl·lica tal i com vam parlar', 'Sala-Cuina-Menjador', 'Paviment', null, 'House Habitat'),
  ('A la porta batent li falten dos cargols a una de les frontisses.', 'A la porta batent li falten dos cargols a una de les frontisses.', 'Bany suite', 'Fusteria', null, 'House Habitat'),
  ('Acabar amb les planxes de ferro que calguin.', 'Acabar amb les planxes de ferro que calguin.', 'Tanca', 'Estructura', null, 'House Habitat'),
  ('Acabats cargols fixació a terra de porta i postes tanca exterior', 'Acabats cargols fixació a terra de porta i postes tanca exterior', 'Tanca', 'Remats i neteja', null, 'House Habitat'),
  ('Tanca zona bústia (no hi és ara)', 'Tanca zona bústia (no hi és ara)', 'Tanca', null, null, 'House Habitat'),
  ('Video porter i apertura per video porter.', 'Video porter i apertura per video porter.', 'Tanca', 'Electricitat', null, 'HH - RAX'),
  ('Tota la connexió elèctrica', 'Tota la connexió elèctrica', 'Tanca', 'Electricitat', null, 'House Habitat'),
  ('Pany porta vianants, està enganxat al límit de la porta.', 'Pany porta vianants, està enganxat al límit de la porta.', 'Tanca', 'Fusteria', null, 'House Habitat'),
  ('Posar un pom o similar per poder tancar bé la porta de vianants', 'Posar un pom o similar per poder tancar bé la porta de vianants', 'Tanca', 'Fusteria', null, 'House Habitat'),
  ('Pintura', 'Pintura', 'Tanca', 'Pintura', null, 'House Habitat'),
  ('Part inferior mur interior, entrant a l''esquerra: deixar ben rematat, possiblement arrebossant.', 'Part inferior mur interior, entrant a l''esquerra: deixar ben rematat, possiblement arrebossant.', 'Tanca', 'Revestiments / Enrajolat', null, 'House Habitat'),
  ('Sobre-barana, trobada amb aplacat façana fa panxa.', 'Sobre-barana, trobada amb aplacat façana fa panxa.', 'Terrassa P1', 'Revestiments / Enrajolat', null, 'House Habitat'),
  ('Òxid de la reixa.', 'Òxid de la reixa.', 'Terrassa P1', null, null, 'House Habitat'),
  ('Tapar cables / tubs cantonada fons esquerre', 'Tapar cables / tubs cantonada fons esquerre', 'Traster', 'Electricitat', null, 'HH - RAX')
) as v(title, description, zone_name, work_type_name, assignee_email, assignee_team);
